version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    volumes:
      - /data/atompi-ci/jenkins_jian:/var/jenkins_home
      - /data/atompi-ci/nfs:/var/jenkins_home/nfs
    ports:
      - 8080:8080

  docker:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - /data/atompi-ci/docker/data:/var/lib/docker
      - /data/atompi-ci/docker/etc:/etc/docker