version: '2'
services:
    gitlab:
      image: 'registry.cn-hangzhou.aliyuncs.com/devops_hu/gitlab:1.0.0'
      restart: unless-stopped
      hostname: locahost
      container_name: gitlab-zh
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.1.31:11080'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['gitlab_ssh_host'] = '192.168.1.31'
          gitlab_rails['gitlab_shell_ssh_port'] = 11022
          # The configuration that needs to be configured in gitlab.rb can be configured here,
          # For example, the following email configuration:
          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          # gitlab_rails['smtp_port'] = 465
          # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
          # gitlab_rails['smtp_password'] = "password"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = true
          # gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
      ports:
        - '11080:11080'
        - '11443:443'
        - '11022:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
volumes:
    config:
    data:
    logs: