version: "3.3"

services:
  coredns:
    image: coredns/coredns:1.7.0
    command: -conf /data/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "9153:9153/tcp"
    volumes:
      - /data/coredns:/data:ro
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"