version: '3.8'
services:
  redis-cratos:
    image: 'hub.gitee.cc/library/redis:5.0.9'
    ports:
      - '192.168.1.60:6379:6379'
    volumes:
      - '/data/redis/cratos/conf/6379.conf:/6379.conf'
    command: /6379.conf
