{
 "title": "Gitee customize process alerts",
 "tags": [ "alert" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "sidekiq_status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{procname!=\"git-srv\",job!=\"giteehost1-pyclient\",job!=\"apk-pyclient\",procname!~\"sidekiqworkercount.*\",procname!=\"sidekiq_process_count\"}",
     "legendFormat": "{{ job }}, {{ procname }}"
    }
   ]
  },
  {
   "title": "git-diamond_status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{procname=\"git-diamond\",job!=\"sto6_prompyclients\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "git-srv_status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{procname=\"git-srv\",job!=\"sto6_prompyclients\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "giteehost1_services_status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{job=\"giteehost1-pyclient\"}",
     "legendFormat": "{{ job }}, {{ procname }}"
    }
   ]
  }
 ]
}