{
 "title": "3rdsvc Alerts",
 "tags": [ "alert" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "3rdsvc_status_code",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{job=\"apk-pyclient\",procname=~\".*status_code\"}",
     "legendFormat": "{{ job }}, {{ procname }}"
    }
   ]
  },
  {
   "title": "3rdsvc_sidekiq_status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{job=\"apk-pyclient\",procname=~\".*_sidekiq.*\"}",
     "legendFormat": "{{ job }}, {{ procname }}"
    }
   ]
  },
  {
   "title": "3rdsvc_port_status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{job=\"apk-pyclient\",procname!~\".*_sidekiq.*\",procname!~\".*_status_code\"}",
     "legendFormat": "{{ job }}, {{ procname }}"
    }
   ]
  }
 ]
}