{
 "title": "cpu-mem资源集合表格--总体排名",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "all-node-cpu-load",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_load1{}[1m])) by (instance)"
    },
    {
     "expr": "sum(avg_over_time(node_load5{}[5m])) by (instance)"
    },
    {
     "expr": "sum(avg_over_time(node_load15{}[15m])) by (instance)"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=~\"user\"}) by (instance)"
    }
   ]
  },
  {
   "title": "all-node-cpuinfo",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (clamp_max(((avg by (cpu,instance) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]),1)) ))*100 ),100)  ) "
    },
    {
     "expr": "avg by (instance) (clamp_max(((avg by (cpu,instance) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"user\"}[5m]),1)) ))*100 ),100)  ) "
    },
    {
     "expr": "100 - ( avg by (instance) ( clamp_max(((avg by (cpu,instance) ( (clamp_max(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]),1)) ))*100 ),100)  ) )"
    }
   ]
  },
  {
   "title": "all-node-memory-info",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemTotal_bytes)"
    },
    {
     "expr": "sum by (instance)  (node_memory_MemAvailable_bytes or (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) "
    },
    {
     "expr": "sum by (instance) ( ( (node_memory_MemTotal_bytes - ( node_memory_MemAvailable_bytes or (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) ) / node_memory_MemTotal_bytes)*100 )"
    }
   ]
  }
 ]
}