{
 "title": "磁盘性能指标趋势图",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "$host -- IOPS读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_reads_completed_total{device=~\"sda\",instance=\"$host\"}[5m])) + (irate(node_disk_writes_completed_total{device=~\"sda\",instance=\"$host\"}[5m]))",
     "legendFormat": "读+写"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"sda\",instance=\"$host\"}[5m])",
     "legendFormat": "读"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"sda\",instance=\"$host\"}[5m])",
     "legendFormat": "写"
    }
   ]
  },
  {
   "title": "$host -- 吞吐量 读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "( irate(node_disk_read_bytes_total{device=~\"sda\",instance=\"$host\"}[5m]) )  +  ( irate(node_disk_written_bytes_total{device=~\"sda\",instance=\"$host\"}[5m]))",
     "legendFormat": "读+写"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"sda\",instance=\"$host\"}[5m])",
     "legendFormat": "读"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"sda\",instance=\"$host\"}[5m])",
     "legendFormat": "写"
    }
   ]
  },
  {
   "title": "$host--IO使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=~\"sda\",instance=\"$host\"}[5m])/10",
     "legendFormat": "IO使用率"
    }
   ]
  },
  {
   "title": "$host--每IO读写完成需要的时间-IO延时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_read_time_seconds_total{device=~\"sda\",instance=\"$host\"}[5m])) / (irate(node_disk_reads_completed_total{device=~\"sda\",instance=\"$host\"}[5m]))",
     "legendFormat": "读"
    },
    {
     "expr": "(irate(node_disk_write_time_seconds_total{device=~\"sda\",instance=\"$host\"}[5m])) / (irate(node_disk_writes_completed_total{device=~\"sda\",instance=\"$host\"}[5m]))",
     "legendFormat": "写"
    }
   ]
  }
 ]
}