{
 "title": "内网带宽流量",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "内网最新值出入带宽排行",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " (sum(irate(node_network_receive_bytes_total{device=~\"em2|eno2\"}[5m]))   by (instance,device) ) * 8 "
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{device=~\"em2|eno2\"}[5m]))   by (instance,device) ) * 8"
    }
   ]
  },
  {
   "title": "所有主机内网网卡-出  入-主机的流量",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{device=~\"em2|eno2\"}[5m]))    ) * 8",
     "legendFormat": "内网  出  流量总和"
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{device=~\"em2|eno2\"}[5m]))    ) * 8",
     "legendFormat": "内网  入  流量总和"
    }
   ]
  },
  {
   "title": "所有主机内网网卡-出-主机的流量",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=~'$host',device=~\"em2|eno2\"}[5m]))   by (instance,device) ) * 8",
     "legendFormat": "{{instance}}--{{device}}"
    }
   ]
  },
  {
   "title": "所有主机内网网卡-入-主机的流量",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{device=~\"em2|eno2\"}[5m]))   by (instance,device) ) * 8",
     "legendFormat": "{{instance}}--{{device}}"
    }
   ]
  }
 ]
}