{
 "title": "公网进出口流量",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "所有主机公网 进  流量总和（receive_bytes）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"em1|eno1\"}[5m])) * 8",
     "legendFormat": "公网所有 进 主机流量和"
    }
   ]
  },
  {
   "title": "所有主机公网 出  流量总和（transmit_bytes）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"em1|eno1\"}[5m])) * 8",
     "legendFormat": "公网所有 出 主机流量和"
    }
   ]
  },
  {
   "title": "公网网口的 进 $host 流量（receive_bytes）",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=~\"$host\", device=~\"em1|eno1\"}[5m])) by (instance,device) ) * 8",
     "legendFormat": "{{instance}}--{{device}}"
    }
   ]
  },
  {
   "title": "公网网口的 出 $host 流量（transmit_bytes）",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(node_network_transmit_bytes_total{instance=~\"$host\", device=~\"em1|eno1\"}[5m])) by (instance,device) ) * 8",
     "legendFormat": "{{instance}}--{{device}}"
    }
   ]
  }
 ]
}