{
 "title": "PyClient Data",
 "tags": [ "PyClient" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(process_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Customize Process Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{instance=\"$host\",procname!~\"sidekiqworkercount.*\"}",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Sidekiq Workers Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_status{procname=~\"sidekiqworkercount.*\",instance=\"$host\"}",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "磁盘使用量增长",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "disk_space_status{instance=\"$host\"}",
     "legendFormat": "/data"
    }
   ]
  }
 ]
}