version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce'
      restart: always
      hostname: locahost
      container_name: gitlab
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.1.31:11080'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['gitlab_ssh_host'] = '192.168.1.31'
          gitlab_rails['gitlab_shell_ssh_port'] = 11022
      ports:
        - '11080:11080'
        - '11443:443'
        - '11022:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab

      dns:
        - 192.168.1.31

volumes:
    config:
    data:
    logs: